version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  # postgresql:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgresql_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb

volumes:
  rabbitmq_data: # postgresql_data:
